"""File templates for ``startproject``/``startapp`` (string.Template, $-based).

$-placeholders keep generated code free of brace-escaping pain.
"""

from __future__ import annotations

from string import Template

__all__ = ["APP_TEMPLATE", "PROJECT_TEMPLATE"]

# -- project ----------------------------------------------------------------------

PROJECT_TEMPLATE: dict[str, Template] = {
    "manage.py": Template(
        '''#!/usr/bin/env python
"""Management shim for $project_name (Ronnie)."""
import os
import sys
from pathlib import Path

# Make `$settings_module` importable from any cwd (project parent on sys.path).
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


def main():
    os.environ.setdefault("RONNIE_SETTINGS_MODULE", "$settings_module")
    from ronnie.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)


if __name__ == "__main__":
    main()
'''
    ),
    "config/__init__.py": Template(""),
    "config/settings.py": Template(
        '''"""
Ronnie settings for $project_name.

Generated by `ronnie startproject`. See PLAN.md §7 for the full reference.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used for sessions/signing secret!
SECRET_KEY = "$secret_key"

# SECURITY WARNING: don't run with DEBUG=True in production.
DEBUG = True

ALLOWED_HOSTS: list[str] = []

# Applications ("apps.<label>" for apps created with `ronnie startapp`).
INSTALLED_APPS: list[str] = [
    "ronnie.contrib.sessions",
    "ronnie.contrib.messages",
    "ronnie.contrib.auth",
    "ronnie.contrib.admin",
    "ronnie.contrib.redirects",
    # "apps.$first_app",
]

# Middleware stack (dotted paths), outermost first.
MIDDLEWARE: list[str] = [
    "ronnie.middleware.security.SecurityMiddleware",
    "ronnie.middleware.host.HostValidationMiddleware",
    "ronnie.contrib.sessions.middleware.SessionMiddleware",
    "ronnie.middleware.csrf.CsrfMiddleware",
    "ronnie.contrib.auth.middleware.AuthMiddleware",
    "ronnie.contrib.messages.middleware.MessagesMiddleware",
    "ronnie.middleware.clickjacking.XFrameOptionsMiddleware",
    "ronnie.contrib.redirects.middleware.RedirectFallbackMiddleware",
]

DATABASES = {
    "default": {
        "ENGINE": "sqlite",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

STATIC_URL = "/static"

TIME_ZONE = "UTC"
USE_TZ = True
'''
    ),
    "config/asgi.py": Template(
        '''"""ASGI entry point for $project_name."""
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
os.environ.setdefault("RONNIE_SETTINGS_MODULE", "$settings_module")

from ronnie.core.asgi import get_asgi_application

application = get_asgi_application()
'''
    ),
    "apps/__init__.py": Template(""),
}

# -- app ---------------------------------------------------------------------------

APP_TEMPLATE: dict[str, Template] = {
    "__init__.py": Template(""),
    "apps.py": Template(
        """from ronnie.apps import AppConfig


class $class_name(AppConfig):
    name = "$app_name"
"""
    ),
    "routes.py": Template(
        """from ronnie.common import P, Titled

from ronnie.core.routing import Router

rt = Router("$label")


@rt
def index():
    return Titled("$verbose_name", P("Welcome to $verbose_name."))
"""
    ),
    "models.py": Template(
        '''"""Data model for $verbose_name.

Convention: declare your row dataclasses here and list them in TABLES;
`ronnie migrate` creates/updates the tables via the MiniDataAPI.

    from dataclasses import dataclass

    @dataclass
    class Post:
        id: int | None = None      # implicit primary key (MiniDataAPI convention)
        title: str = ""
        body: str = ""

    TABLES: list[type] = [Post]
"""

TABLES: list[type] = []
'''
    ),
    "migrations/__init__.py": Template('"""Migrations for this app."""\n'),
    "tests/__init__.py": Template(""),
    "tests/test_routes.py": Template(
        """from ronnie.testing import RonnieTestClient


def test_index(client: RonnieTestClient):
    response = client.get("/$label/")
    assert response.status_code == 200
"""
    ),
    "management/__init__.py": Template(""),
    "management/commands/__init__.py": Template(""),
}
