"""File templates for ``startproject``/``startapp`` (string.Template, $-based).

$-placeholders keep generated code free of brace-escaping pain.
"""

from __future__ import annotations

from string import Template

__all__ = ["APP_TEMPLATE", "PROJECT_TEMPLATE"]

# -- project ----------------------------------------------------------------------

PROJECT_TEMPLATE: dict[str, Template] = {
    "manage.py": Template(
        '''#!/usr/bin/env python
"""Management shim for $project_name (Ronnie)."""
import os
import sys


def main():
    os.environ.setdefault("RONNIE_SETTINGS_MODULE", "$settings_module")
    from ronnie.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)


if __name__ == "__main__":
    main()
'''
    ),
    "config/__init__.py": Template(""),
    "config/settings.py": Template(
        '''"""
Ronnie settings for $project_name.

Generated by `ronnie startproject`. See PLAN.md §7 for the full reference.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used for sessions/signing secret!
SECRET_KEY = "$secret_key"

# SECURITY WARNING: don't run with DEBUG=True in production.
DEBUG = True

ALLOWED_HOSTS: list[str] = []

# Applications ("apps.<label>" for apps created with `ronnie startapp`).
INSTALLED_APPS: list[str] = [
    # "apps.$first_app",
]

# Middleware stack (dotted paths), outermost first. Ronnie contribs add theirs.
MIDDLEWARE: list[str] = []

DATABASES = {
    "default": {
        "ENGINE": "sqlite",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

STATIC_URL = "/static"

TIME_ZONE = "UTC"
USE_TZ = True
'''
    ),
    "config/asgi.py": Template(
        '''"""ASGI entry point for $project_name."""
import os

os.environ.setdefault("RONNIE_SETTINGS_MODULE", "$settings_module")

from ronnie.core.asgi import get_asgi_application

application = get_asgi_application()
'''
    ),
    "apps/__init__.py": Template(""),
}

# -- app ---------------------------------------------------------------------------

APP_TEMPLATE: dict[str, Template] = {
    "__init__.py": Template(""),
    "apps.py": Template(
        """from ronnie.apps import AppConfig


class $class_name(AppConfig):
    name = "$app_name"
"""
    ),
    "routes.py": Template(
        """from fasthtml.common import P, Titled

from ronnie.core.routing import Router

rt = Router("$label")


@rt
def index():
    return Titled("$verbose_name", P("Welcome to $verbose_name."))
"""
    ),
    "models.py": Template(
        '''"""Data model for $verbose_name.

Convention: declare your row dataclasses here and list them in TABLES;
`ronnie migrate` creates/updates the tables via the MiniDataAPI.

    from dataclasses import dataclass

    @dataclass
    class Post:
        title: str
        body: str = ""

    TABLES: list[type] = [Post]
"""

TABLES: list[type] = []
'''
    ),
    "tests/__init__.py": Template(""),
    "tests/test_routes.py": Template(
        """from ronnie.testing import RonnieTestClient


def test_index(client: RonnieTestClient):
    response = client.get("/$label/")
    assert response.status_code == 200
"""
    ),
    "management/__init__.py": Template(""),
    "management/commands/__init__.py": Template(""),
}
